### ISSUE TITLE
Issue in the Command file

### ISSUE THREAD

**Issue by sponegg** [djewett/latest_items#1]
if right clicking into the white space of a listing there's no item selected so this line breaks:

var item = $models.getItem(selection.getItem(0));

It's located in the isAvailable:

    isAvailable: function (selection) {
        // Gets the selected item in Tridion GUI
        var items = selection.getItems();
        var item = $models.getItem(selection.getItem(0));
        // Checks if a container item has been selected.
        if ($models.isContainerItemType(item.getItemType())) {
            return true;
        }
        else {
            return false;
        }
    },

here's a sample of code that I use that you can take the bits that you need:

    isAvailable: function (selection) {
        var item = this._getSelectedItem(selection);
        if (item != null) {
            switch ($models.getItemType(item)) {
                case $const.ItemType.PUBLICATION:
                    return true;
            }
        }

        return false;
    },

and the function in there:

    _getSelectedItem: function (selection) {
        $assert.isObject(selection);

        switch (selection.getCount()) {
            case 0: return (selection.getParentItemUri) ? selection.getParentItemUri() : null;
            case 1: return selection.getItem(0);
            default: return null;
        }
    },

**Comment by djewett** [comment]
We were unable to reproduce this issues following the steps provided. However, the code has been updated, according to your suggestion. See commit here:

https://github.com/djewett/latest_items/commit/dd7adb794b25e723c06e1b9fd473a04c9176252b

In addition, several related context menu issues were resolved.
